version: "{build}"

init:
  - cmd: echo init

branches:
  only:
    - master

image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

configuration:
  - Release
  - Debug

before_build:
  - cmd: |- 
    echo fuck
    cmake -B"." -H"."

for:
  - matrix:
      only:
        - configuration: Release
    build_script:
      - cmd: cmake --build . --config Release --target vulkan_samples
  - matrix:
      only:
        - configuration: Debug
    build_script:
      - cmd: cmake --build . --config Debug --target vulkan_samples

before_test:
  - cmd: echo hello
